# Generated by Django 3.0.1 on 2020-06-12 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("preboarding", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preboarding",
            name="to_do",
        ),
    ]
