# Generated by Django 3.1.2 on 2020-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("preboarding", "0002_remove_preboarding_to_do"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preboarding",
            name="form",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
