# Generated by Django 3.2.8 on 2021-11-09 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('preboarding', '0003_auto_20201013_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='preboarding',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_preboarding.preboarding_set+', to='contenttypes.contenttype'),
        ),
    ]
