# Generated by Django 3.2.10 on 2022-02-09 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preboarding", "0008_auto_20220209_0048"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preboarding",
            name="content",
        ),
    ]
