# Generated by Django 3.2.10 on 2022-02-09 00:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preboarding", "0009_remove_preboarding_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preboarding",
            old_name="content_json",
            new_name="content",
        ),
    ]
