# Generated by Django 3.2.10 on 2022-02-09 00:51

from django.db import migrations

import misc.fields


class Migration(migrations.Migration):
    dependencies = [
        ("preboarding", "0010_rename_content_json_preboarding_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preboarding",
            name="content",
            field=misc.fields.ContentJSONField(default=dict),
        ),
    ]
