# Generated by Django 3.2.10 on 2022-02-09 00:44

from django.db import migrations

from misc.migration_scripts.content_migrations import (
    RunPythonWithArguments,
    migrate_forms_to_wysiwyg,
)

class Migration(migrations.Migration):

    dependencies = [
        ('preboarding', '0011_alter_preboarding_content'),
    ]

    operations = [
        RunPythonWithArguments(
            migrate_forms_to_wysiwyg, context={"app": "preboarding", "model": "preboarding"},
        ),
    ]
