# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("preboarding", "0016_alter_preboarding_departments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="preboarding",
            options={"ordering": ("name",)},
        ),
    ]
