# Generated by Django 3.2.8 on 2021-11-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("resources", "0003_auto_20201013_0149"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_resources.resource_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
