# Generated by Django 3.2.10 on 2022-02-10 22:23

from django.db import migrations, models

import misc.fields
from misc.migration_scripts.content_migrations import (RunPythonWithArguments,
                                                       migrate_wysiwyg_field)


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_alter_resource_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="content_json",
            field=misc.fields.ContentJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="courseanswer",
            name="answers",
            field=models.JSONField(default=list),
        ),
        RunPythonWithArguments(
            migrate_wysiwyg_field, context={"app": "resources", "model": "chapter"}
        ),
    ]
