# Generated by Django 3.2.10 on 2022-02-10 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0007_auto_20220210_2223"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="content",
        ),
    ]
