# Generated by Django 3.2.10 on 2022-02-10 23:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0008_remove_chapter_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="content_json",
            new_name="content",
        ),
    ]
