# Generated by Django 3.2.10 on 2022-02-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0009_rename_content_json_chapter_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
