# Generated by Django 3.2.10 on 2022-02-14 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0010_chapter_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"ordering": ("order", "pk")},
        ),
    ]
