# Generated by Django 3.2.12 on 2022-04-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0013_auto_20220221_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="on_day",
            field=models.IntegerField(
                default=1, verbose_name="Workday that this item is due"
            ),
        ),
    ]
