# Generated by Django 3.2.13 on 2022-09-29 01:02

from django.db import migrations
from django.db.models import Count


class Migration(migrations.Migration):
    def clear_empty_resources(apps, schema_editor):
        Resource = apps.get_model("resources", "Resource")
        Resource.objects.annotate(num_chapters=Count("chapters")).filter(
            num_chapters=0
        ).delete()

    dependencies = [
        ("resources", "0014_alter_resource_on_day"),
    ]

    operations = [
        migrations.RunPython(clear_empty_resources),
    ]
