# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0018_alter_resource_departments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ("name",)},
        ),
    ]
