FROM python:3

RUN apt install curl
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt install -y nodejs
RUN npm install -g npm@latest
COPY front /usr/src/front
WORKDIR /usr/src/front

RUN npm install
RUN npm run build
RUN npm run generate

ENV PATH /home/django/.local/bin:$PATH
WORKDIR /usr/src/app
COPY back/ .
RUN pip install --no-cache-dir -r requirements.txt

RUN cp -R /usr/src/front/dist/* ./static/js/
RUN cp /usr/src/front/dist/index.html ./organization/templates/index.html

RUN python manage.py collectstatic --noinput --clear

EXPOSE 8000
CMD ["gunicorn", "back.wsgi:application", "-b :8000"]
