FROM python:3

COPY back /usr/src/back
ENV PATH /home/django/.local/bin:$PATH
WORKDIR /usr/src/back
RUN pip install --no-cache-dir -r requirements.txt

RUN python manage.py collectstatic --noinput --clear

EXPOSE 8000

