# Generated by Django 3.0.1 on 2020-06-06 20:14

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10200), blank=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('template', models.BooleanField(default=True)),
                ('content', models.ManyToManyField(to='misc.Content')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
