# Generated by Django 3.0.7 on 2020-09-24 20:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='channel',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='form',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name=models.TextField(default='[]')),
        ),
    ]
