# Generated by Django 3.1.3 on 2020-12-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20201013_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='integration',
            field=models.CharField(blank=True, choices=[('github', 'Github')], default='', max_length=10),
        ),
    ]
