# Generated by Django 4.2.20 on 2025-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('subject', models.CharField(max_length=255, verbose_name='Email Subject')),
                ('category', models.CharField(choices=[('welcome', 'Welcome Emails'), ('task', 'Task Notifications'), ('reminder', 'Reminders'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Category')),
                ('content', models.JSONField(default=dict, help_text='Content in Editor.js JSON format', verbose_name='Email Content')),
                ('description', models.TextField(blank=True, help_text='Internal description of when this template should be used', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
    ]
