# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("introductions", "0007_alter_introduction_departments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="introduction",
            options={"ordering": ("name",)},
        ),
    ]
