# Generated by Django 3.2.10 on 2022-01-17 22:59

from django.db import migrations

from misc.migration_scripts.content_migrations import (
    RunPythonWithArguments,
    migrate_wysiwyg_field,
)


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0004_badge_content_json"),
    ]

    operations = [
        RunPythonWithArguments(
            migrate_wysiwyg_field, context={"app": "badges", "model": "badge"}
        ),
    ]
