# Generated by Django 3.2.10 on 2022-01-17 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("badges", "0005_auto_20220117_2259"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="content",
        ),
    ]
