# Generated by Django 3.2.10 on 2022-01-17 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0004_auto_20210511_1242"),
        ("badges", "0006_remove_badge_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="misc.file",
            ),
        ),
    ]
