# Generated by Django 3.2.10 on 2022-02-01 17:03

from django.db import migrations

import misc.fields


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0007_alter_badge_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="content_json",
            field=misc.fields.ContentJSONField(default=dict),
        ),
    ]
