# Generated by Django 3.2.12 on 2022-02-21 13:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import misc.fields


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_auto_20210511_1242'),
        ('badges', '0009_rename_content_json_badge_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='content',
            field=misc.fields.ContentJSONField(default=dict, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misc.file', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=240, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10200), blank=True, size=None, verbose_name='Tags'),
        ),
    ]
