# Generated by Django 5.2.6 on 2025-09-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0010_auto_20220221_1338'),
        ('users', '0044_alter_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='departments',
            field=models.ManyToManyField(blank=True, to='users.department'),
        ),
    ]
