# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0012_alter_badge_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ('name',)},
        ),
    ]
