# Generated by Django 3.2.10 on 2022-01-28 00:04

from django.db import migrations
import misc.fields

from misc.migration_scripts.content_migrations import (
    RunPythonWithArguments,
    migrate_wysiwyg_field,
)

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='content_json',
            field=misc.fields.ContentJSONField(default=dict),
        ),
        RunPythonWithArguments(
            migrate_wysiwyg_field, context={"app": "appointments", "model": "Appointment"}
        ),
    ]
