# Generated by Django 3.2.10 on 2022-01-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_appointment_content_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="content",
        ),
    ]
