# Generated by Django 3.2.10 on 2022-01-28 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='content_json',
            new_name='content',
        ),
    ]
