# Generated by Django 3.2.13 on 2022-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20220221_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, default='2022-06-06', null=True, verbose_name='Date'),
        ),
    ]
