# Generated by Django 5.2.6 on 2025-09-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0009_appointment_departments"),
        ("users", "0044_alter_user_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to make it available for all managers/admins",
                to="users.department",
            ),
        ),
    ]
