# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_alter_appointment_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('name',)},
        ),
    ]
