FROM python:latest
ENV PATH /home/django/.local/bin:$PATH

RUN groupadd -r django && useradd -r -m -g django django
USER django:django

WORKDIR /home/django/app
COPY --chown=django:django . /home/django/app
RUN pip install --user -r requirements.txt
RUN python manage.py collectstatic --noinput --clear