from django.urls import path

from . import views

app_name = "people"
urlpatterns = [
    path("", views.NewHireListView.as_view(), name="new_hires"),
    path("new_hire/add/", views.NewHireAddView.as_view(), name="new_hire_add"),
    path(
        "new_hire/<int:pk>/overview/",
        views.NewHireSequenceView.as_view(),
        name="new_hire",
    ),
    path(
        "new_hire/<int:pk>/profile/",
        views.NewHireProfileView.as_view(),
        name="new_hire_profile",
    ),
    path(
        "new_hire/<int:pk>/notes/",
        views.NewHireNotesView.as_view(),
        name="new_hire_notes",
    ),
    path(
        "new_hire/<int:pk>/welcome_messages/",
        views.NewHireWelcomeMessagesView.as_view(),
        name="new_hire_welcome_messages",
    ),
    path(
        "new_hire/<int:pk>/admin_tasks/",
        views.NewHireAdminTasksView.as_view(),
        name="new_hire_admin_tasks",
    ),
    path(
        "new_hire/<int:pk>/forms/",
        views.NewHireFormsView.as_view(),
        name="new_hire_forms",
    ),
    path(
        "new_hire/<int:pk>/progress/",
        views.NewHireProgressView.as_view(),
        name="new_hire_progress",
    ),
    path(
        "new_hire/<int:pk>/course_answers/<int:resource_user>/",
        views.NewHireCourseAnswersView.as_view(),
        name="new-hire-rating",
    ),
    path(
        "new_hire/<int:pk>/tasks/",
        views.NewHireTasksView.as_view(),
        name="new_hire_tasks",
    ),
    path(
        "new_hire/<int:pk>/access/",
        views.NewHireAccessView.as_view(),
        name="new_hire_access",
    ),
    path(
        "new_hire/<int:pk>/check_access/<int:integration_id>/",
        views.NewHireCheckAccessView.as_view(),
        name="new_hire_check_integration",
    ),
    path(
        "new_hire/<int:pk>/give_access/<int:integration_id>/",
        views.NewHireGiveAccessView.as_view(),
        name="new_hire_give_integration",
    ),
    path(
        "new_hire/<int:pk>/task/<slug:type>/",
        views.NewHireTaskListView.as_view(),
        name="new_hire_task_list",
    ),
    path(
        "new_hire/<int:pk>/task/<int:template_id>/<slug:type>/",
        views.NewHireToggleTaskView.as_view(),
        name="toggle_new_hire_task",
    ),
    path(
        "new_hire/<int:pk>/send_login_email/",
        views.NewHireSendLoginEmailView.as_view(),
        name="send_login_email",
    ),
    path(
        "new_hire/<int:pk>/delete/",
        views.NewHireDeleteView.as_view(),
        name="delete",
    ),
    path(
        "new_hire/<int:pk>/migrate_to_normal/",
        views.NewHireMigrateToNormalAccountView.as_view(),
        name="migrate-to-normal",
    ),
    path(
        "new_hire/<int:pk>/add_sequence/",
        views.NewHireAddSequenceView.as_view(),
        name="add_sequence",
    ),
    path(
        "new_hire/<int:pk>/trigger_condition/<int:condition_pk>/",
        views.NewHireTriggerConditionView.as_view(),
        name="trigger-condition",
    ),
    path(
        "new_hire/<int:pk>/send_preboarding_notification/",
        views.NewHireSendPreboardingNotificationView.as_view(),
        name="send_preboarding_notification",
    ),
    path("colleagues/", views.ColleagueListView.as_view(), name="colleagues"),
    path(
        "colleagues/create/",
        views.ColleagueCreateView.as_view(),
        name="colleague_create",
    ),
    path(
        "colleagues/syncslack/",
        views.ColleagueSyncSlack.as_view(),
        name="sync-slack",
    ),
    path(
        "colleagues/<int:pk>/connect_to_slack/",
        views.ColleagueGiveSlackAccessView.as_view(),
        name="connect-to-slack",
    ),
    path(
        "colleagues/<int:pk>/toggle_portal_access/",
        views.ColleagueTogglePortalAccessView.as_view(),
        name="toggle-portal-access",
    ),
    path("colleagues/<int:pk>/", views.ColleagueUpdateView.as_view(), name="colleague"),
    path(
        "colleagues/<int:pk>/delete/",
        views.ColleagueDeleteView.as_view(),
        name="colleague_delete",
    ),
    path(
        "colleagues/<int:pk>/resource/",
        views.ColleagueResourceView.as_view(),
        name="add_resource",
    ),
    path(
        "colleagues/<int:pk>/resource/<int:template_id>/",
        views.ColleagueToggleResourceView.as_view(),
        name="toggle_resource",
    ),
]
