# Generated by Django 3.0.1 on 2020-06-06 20:14

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("misc", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="WelcomeMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=20250)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("nl", "Dutch"),
                            ("fr", "French"),
                            ("de", "Deutsch"),
                            ("tr", "Turkish"),
                            ("pt", "Portuguese"),
                            ("es", "Spanish"),
                        ],
                        default="en",
                        max_length=3,
                    ),
                ),
                (
                    "message_type",
                    models.IntegerField(
                        choices=[
                            (0, "pre-boarding"),
                            (1, "new hire welcome"),
                            (2, "text welcome"),
                            (3, "slack welcome"),
                            (4, "slack knowledge"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("nl", "Dutch"),
                            ("fr", "French"),
                            ("de", "Deutsch"),
                            ("tr", "Turkish"),
                            ("pt", "Portuguese"),
                            ("es", "Spanish"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=1000)),
                ("base_color", models.CharField(default="#99835C", max_length=10)),
                ("accent_color", models.CharField(default="#ffbb42", max_length=10)),
                ("bot_color", models.CharField(default="#ffbb42", max_length=10)),
                ("credentials_login", models.BooleanField(default=True)),
                ("google_login", models.BooleanField(default=False)),
                ("slack_login", models.BooleanField(default=False)),
                ("new_hire_email", models.BooleanField(default=True)),
                ("new_hire_email_reminders", models.BooleanField(default=True)),
                (
                    "new_hire_email_overdue_reminders",
                    models.BooleanField(default=False),
                ),
                ("slack_buttons", models.BooleanField(default=True)),
                ("ask_colleague_welcome_message", models.BooleanField(default=True)),
                ("send_new_hire_start_reminder", models.BooleanField(default=False)),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="misc.File",
                    ),
                ),
            ],
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
