# Generated by Django 3.1.3 on 2020-12-02 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="auto_create_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="create_new_hire_without_confirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="slack_confirm_person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
