# Generated by Django 3.2.8 on 2021-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20211108_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='changelog',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
