# Generated by Django 3.2.10 on 2022-01-26 00:04

from django.db import migrations


class Migration(migrations.Migration):
    # This migration is needed due to folder structure changes.
    # If this is not migrated, then Django Q will show NoneType errors
    # as it can't find the correct functions then.

    def edit_schedules(apps, schema_editor):
        from django_q.models import Schedule

        schedule = Schedule.objects.get(func="sequences.tasks.timed_triggers")
        schedule.func = "admin.sequences.tasks.timed_triggers"
        schedule.save()

        schedule = Schedule.objects.get(func="integrations.tasks.create_accounts")
        schedule.func = "admin.integrations.tasks.create_accounts"
        schedule.save()

    dependencies = [
        ("organization", "0005_auto_20211109_0307"),
    ]

    operations = [
        migrations.RunPython(edit_schedules),
    ]
