# Generated by Django 3.2.10 on 2022-01-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack_bot", "0001_initial"),
        ("organization", "0006_auto_20220126_0004"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="slack_default_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="slack_bot.slackchannel",
            ),
        ),
    ]
