# Generated by Django 3.2.10 on 2022-02-16 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0007_organization_slack_default_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('public_to_new_hire', models.BooleanField(default=False)),
                ('reverse_link', models.CharField(max_length=200)),
                ('reverse_link_params', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_owners', to=settings.AUTH_USER_MODEL)),
                ('created_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_receivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
