# Generated by Django 3.2.10 on 2022-02-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0008_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="reverse_link",
            field=models.CharField(default="", max_length=200),
        ),
    ]
