# Generated by Django 3.2.13 on 2022-05-04 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20220419_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timed_triggers_last_check',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
