# Generated by Django 3.2.13 on 2022-05-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0016_auto_20220512_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notified_user",
            field=models.BooleanField(default=False),
        ),
    ]
