# Generated by Django 3.2.13 on 2022-05-20 00:48

from django.db import migrations


class Migration(migrations.Migration):
    def load_schedules(apps, schema_editor):
        from django_q.models import Schedule

        schedule = Schedule.objects.get(
            func="admin.sequences.tasks.timed_triggers",
        )
        schedule.cron = ("*/5 * * * *",)
        schedule.save()

        Schedule.objects.filter(
            func="admin.integrations.tasks.create_accounts",
        ).delete()

    dependencies = [
        ("organization", "0017_notification_notified_user"),
    ]

    operations = [
        migrations.RunPython(load_schedules),
    ]
