# Generated by Django 3.2.13 on 2022-06-10 23:58

from django.db import migrations


class Migration(migrations.Migration):
    def name_schedules(apps, schema_editor):
        from django_q.models import Schedule

        schedule = Schedule.objects.get(
            func="slack_bot.tasks.update_new_hire",
        )
        schedule.name = "Update new hires on tasks"
        schedule.save()

        schedule = Schedule.objects.get(
            func="admin.sequences.tasks.timed_triggers",
        )
        schedule.name = "Timed sequence triggers"
        schedule.save()

        schedule = Schedule.objects.get(
            func="slack_bot.tasks.link_slack_users",
        )
        schedule.name = "Link slack users"
        schedule.save()

        schedule = Schedule.objects.get(
            func="slack_bot.tasks.first_day_reminder",
        )
        schedule.name = "First day reminder"
        schedule.save()

    dependencies = [
        ('organization', '0019_auto_20220523_1620'),
    ]

    operations = [
        migrations.RunPython(name_schedules),
    ]
