# Generated by Django 3.2.13 on 2022-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0024_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="blocks",
            field=models.JSONField(default=list),
        ),
    ]
