# Generated by Django 3.2.13 on 2022-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    def remove_old_error_tracebacks(apps, schema_editor):
        from organization.models import Notification

        Notification.objects.filter(
            notification_type="failed_integration",
        ).update(description="")

    dependencies = [
        ('organization', '0025_notification_blocks'),
    ]

    operations = [
        migrations.RunPython(remove_old_error_tracebacks),
    ]
