# Generated by Django 3.2.16 on 2023-03-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0032_alter_organization_timezone"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.CheckConstraint(
                check=models.Q(("id", 1)), name="only_one_allowed"
            ),
        ),
    ]
