# Generated by Django 3.2.18 on 2023-05-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0033_organization_only_one_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='oidc_login',
            field=models.BooleanField(default=False, verbose_name='Allow users to login with OIDC'),
        ),
    ]
