# Generated by Django 4.2.2 on 2023-06-13 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0034_alter_organization_timezone"),
        ("organization", "0034_organization_oidc_login"),
    ]

    operations = []
