# Generated by Django 4.2.3 on 2023-09-03 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0035_merge_20230613_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ignored_user_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=list, size=None
            ),
        ),
    ]
