# Generated by Django 4.2.5 on 2023-09-11 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0035_merge_20230613_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ignored_user_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                default=list,
                help_text="Emails which get ignored by the importer",
                size=None,
            ),
        ),
    ]
