# Generated by Django 4.2.3 on 2023-08-30 01:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0036_organization_ignored_user_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="ignored_user_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=list, size=None
            ),
        ),
    ]
