# Generated by Django 4.2.11 on 2024-04-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0039_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("tr", "Turkish"),
                    ("pt", "Portuguese"),
                    ("jp", "Japanese"),
                    ("es", "Spanish"),
                    ("cs", "Czech"),
                ],
                default="en",
                max_length=10,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="welcomemessage",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("nl", "Dutch"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("tr", "Turkish"),
                    ("pt", "Portuguese"),
                    ("jp", "Japanese"),
                    ("es", "Spanish"),
                    ("cs", "Czech"),
                ],
                default="en",
                max_length=3,
            ),
        ),
    ]
