# Generated by Django 4.2.23 on 2025-07-04 23:44

from django.db import migrations


class Migration(migrations.Migration):
    def add_japanese_czech_welcome_messages(apps, schema_editor):
        WelcomeMessage = apps.get_model("organization", "WelcomeMessage")
        WelcomeMessage.objects.create(
            language="jp",
            message_type=0,
            message="私たちのことを少しでも知っていただき、スムーズにご入会いただけるよう、オンライン・ウェブページを開設しました。下のボタンをクリックしてご覧ください。",
        )
        WelcomeMessage.objects.create(
            language="jp",
            message_type=1,
            message="オンラインウェブページをご用意しました。ログイン情報は以下の通りです。",
        )
        WelcomeMessage.objects.create(
            language="jp",
            message_type=2,
            message="チームへようこそ、{{first_name}}。ようこそ。最初の数日間に万全を期すため、こちらのリンクをクリックしてください：",
        )
        WelcomeMessage.objects.create(
            language="jp",
            message_type=3,
            message="ようこそ 私たちは、あなたが私たちと一緒にいることを非常に興奮しています。私はオンボーディングボットです。オンボーディングプロセスを通してあなたをサポートします。あなたに必要な情報を提供し、その日に必要なタスクを毎日返信します。私がお手伝いできることをお知りになりたい場合は、help.と入力してください！",
        )
        WelcomeMessage.objects.create(
            language="jp",
            message_type=4,
            message="こんにちは！ナレッジベースをご用意しました！下のボタンをクリックして中身をご覧ください。または、私に質問してください。）",
        )
        WelcomeMessage.objects.create(
            language="cs",
            message_type=0,
            message="Vytvořili jsme pro vás online webovou stránku, abyste se s námi mohli blíže seznámit a hladce se zapojit do provozu. Klikněte na tlačítko níže, abyste si ji prohlédli",
        )
        WelcomeMessage.objects.create(
            language="cs",
            message_type=1,
            message="Vytvořili jsme pro vás online webovou stránku, abyste se s námi mohli blíže seznámit a hladce se zapojit do provozu. Vaše přihlašovací údaje jsou",
        )
        WelcomeMessage.objects.create(
            language="cs",
            message_type=2,
            message="Vítejte v týmu, {{first_name}}. Jsme rádi, že tě máme. Abyste se ujistili, že jste na první dny připraveni, klikněte na tento odkaz:",
        )
        WelcomeMessage.objects.create(
            language="cs",
            message_type=3,
            message="Vítejte! Jsme velmi rádi, že jste mezi námi. Jsem Onboardingbot a pomůžu vám s procesem nástupu. Poskytnu vám všechny potřebné informace a každý den se vám ozvu s úkoly, které musíte ten den splnit. Pokud chcete vědět, co pro vás mohu udělat, napište: help.\nPřeji vám příjemné chvíle s námi, příteli!",
        )
        WelcomeMessage.objects.create(
            language="cs",
            message_type=4,
            message="Ahoj! Mám pro vás k dispozici znalostní databázi! Klikněte na tlačítko níže a podívejte se, co v ní najdete. Nebo mi prostě položte otázku a já se vám pokusím najít odpověď :)",
        )

    dependencies = [
        ("organization", "0041_alter_organization_timezone"),
    ]

    operations = [
        migrations.RunPython(
            add_japanese_czech_welcome_messages, reverse_code=migrations.RunPython.noop
        ),
    ]
