# Generated by Django 4.2.23 on 2025-07-05 00:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0042_alter_organization_timezone"),
        ("organization", "0042_auto_20250704_2344"),
    ]

    operations = []
