# Generated by Django 5.2.6 on 2025-09-13 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0043_auto_20250705_0014"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="credentials_login",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="google_login",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="oidc_login",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="slack_login",
        ),
    ]
