# Generated by Django 4.2.20 on 2025-05-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0043_organization_ai_default_context_organization_ai_default_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email_admin_task_comments',
            field=models.BooleanField(default=True, help_text='Notify administrators when someone comments on their tasks', verbose_name='Send email notifications for admin task comments'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_admin_task_notifications',
            field=models.BooleanField(default=True, help_text='Notify administrators when they are assigned tasks or when tasks are updated', verbose_name='Send email notifications for admin tasks'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_admin_updates',
            field=models.BooleanField(default=True, help_text='Notify administrators about important system updates and changes', verbose_name='Send email notifications for system updates'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_from_name',
            field=models.CharField(blank=True, default='', help_text="The name that will appear in the 'From' field of emails (e.g., 'Your Company Onboarding')", max_length=255, verbose_name="Email 'From' name"),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_signature',
            field=models.TextField(blank=True, default='', help_text='This signature will be added to all outgoing emails', verbose_name='Email signature'),
        ),
    ]
