# Generated by Django 4.2.20 on 2025-05-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_migrate_email_settings'),
        ('organization', '0044_organization_email_admin_task_comments_and_more'),
    ]

    operations = [
    ]
