# Generated by Django 4.2.20 on 2025-05-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0046_add_mailersend_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='custom_email_template',
            field=models.TextField(blank=True, default='', help_text='Leave blank to use the default one. See documentation if you want to use your own.', verbose_name='Base email template'),
        ),
    ]
