# Generated by Django 3.0.1 on 2020-06-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "option",
                    models.IntegerField(
                        choices=[(0, "No"), (1, "Email"), (2, "Slack")]
                    ),
                ),
                ("slack_user", models.CharField(max_length=12500, null=True)),
                ("email", models.EmailField(max_length=12500, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminTaskComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=12500)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="admin_tasks.AdminTask",
                    ),
                ),
            ],
        ),
    ]
