# Generated by Django 3.2.10 on 2022-01-28 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_tasks", "0005_alter_admintaskcomment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admintask",
            options={"ordering": ["completed", "date"]},
        ),
    ]
