# Generated by Django 3.2.12 on 2022-04-19 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tasks", "0007_auto_20220221_1338"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admintask",
            old_name="slack_user",
            new_name="slack_user_old",
        ),
    ]
