# Generated by Django 3.2.12 on 2022-04-19 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    def migrate_slack_user_fields(apps, schema_editor):

        AdminTask = apps.get_model("admin_tasks", "AdminTask")
        User = apps.get_model("users", "User")
        for admin_task in AdminTask.objects.filter(
            slack_user_old__isnull=False
        ).exclude(slack_user_old=""):
            slack_user_exists = User.objects.filter(
                slack_user_id=admin_task.slack_user_old
            ).exists()
            if slack_user_exists:
                admin_task.slack_user = User.objects.filter(
                    slack_user_id=admin_task.slack_user_old
                ).first()
                admin_task.save()

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_tasks", "0008_rename_slack_user_admintask_slack_user_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintask",
            name="slack_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slack_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Slack user",
            ),
        ),
        migrations.RunPython(migrate_slack_user_fields),
    ]
