# Generated by Django 3.2.12 on 2022-04-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_tasks", "0009_admintask_slack_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admintask",
            name="slack_user_old",
        ),
    ]
