# Generated by Django 4.2.5 on 2023-09-21 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0041_condition_condition_admin_tasks_and_more"),
        ("admin_tasks", "0010_remove_admintask_slack_user_old"),
    ]

    operations = [
        migrations.AddField(
            model_name="admintask",
            name="based_on",
            field=models.ForeignKey(
                help_text="If generated through a sequence, then this will be filled",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sequences.pendingadmintask",
            ),
        ),
    ]
