# Generated by Django 4.2.5 on 2023-11-07 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tasks", "0012_admintask_create_integration_admintask_integration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admintask",
            old_name="integration",
            new_name="manual_integration",
        ),
        migrations.RemoveField(
            model_name="admintask",
            name="create_integration",
        ),
    ]
