# Generated by Django 4.2.6 on 2023-10-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tasks", "0012_admintask_create_integration_admintask_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admintask",
            name="create_integration",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Specifies if integration has been created or removed by completing"
                    " the admin task."
                ),
            ),
        ),
    ]
