# Generated by Django 3.2.8 on 2021-11-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_auto_20200606_2014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(),
        ),
    ]
