# Generated by Django 4.2.6 on 2023-11-01 23:44

import django.contrib.postgres.fields
from django.db import migrations, models
import misc.fields
import misc.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240, verbose_name="Name")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10200),
                        blank=True,
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("template", models.BooleanField(default=True)),
                (
                    "content",
                    misc.fields.ContentJSONField(default=dict, verbose_name="Content"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(misc.mixins.ContentMixin, models.Model),
        ),
    ]
