# Generated by Django 4.2.6 on 2023-11-03 00:20

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import misc.fields
import misc.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=240, verbose_name="Name")),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10200),
                        blank=True,
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("template", models.BooleanField(default=True)),
                (
                    "content",
                    misc.fields.ContentJSONField(default=dict, verbose_name="Content"),
                ),
                (
                    "person_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Manager"), (2, "Buddy"), (3, "Custom")],
                        help_text=(
                            "Leave empty to automatically remove/add hardware without "
                            "notifications."
                        ),
                        null=True,
                        verbose_name="Assigned to",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_user_hardware",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pick user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(misc.mixins.ContentMixin, models.Model),
        ),
    ]
