# Generated by Django 4.2.6 on 2023-11-02 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hardware", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user_hardware",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pick user",
            ),
        ),
        migrations.AddField(
            model_name="hardware",
            name="person_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Manager"), (2, "Buddy"), (3, "Custom")],
                help_text="Leave empty to automatically remove/add hardware without notifications.",
                null=True,
                verbose_name="Assigned to",
            ),
        ),
    ]
