# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0003_alter_hardware_departments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hardware",
            options={"ordering": ("name",)},
        ),
    ]
