# Generated by Django 3.0.1 on 2020-06-20 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_scheduledaccess_new_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='one_time_auth_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='integration',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Slack Account'), (2, 'Google'), (3, 'Google Login')]),
        ),
        migrations.AlterField(
            model_name='scheduledaccess',
            name='integration',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Slack Account'), (2, 'Google'), (3, 'Google Login')]),
        ),
    ]
