# Generated by Django 3.1.3 on 2020-12-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20200924_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='integration',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Slack Account'), (2, 'Google'), (3, 'Google Login'), (4, 'Asana')]),
        ),
        migrations.AlterField(
            model_name='scheduledaccess',
            name='integration',
            field=models.IntegerField(choices=[(0, 'Slack'), (1, 'Slack Account'), (2, 'Google'), (3, 'Google Login'), (4, 'Asana')]),
        ),
    ]
