# Generated by Django 3.0.1 on 2020-06-06 20:14

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration",
                    models.IntegerField(
                        choices=[
                            (0, "Slack"),
                            (1, "Slack Account"),
                            (2, "Google"),
                            (3, "GoogleLogin"),
                        ]
                    ),
                ),
                (
                    "token",
                    fernet_fields.fields.EncryptedTextField(blank=True, max_length=10000, null=True),
                ),
                (
                    "refresh_token",
                    fernet_fields.fields.EncryptedTextField(blank=True, max_length=10000, null=True),
                ),
                ("base_url", models.CharField(blank=True, max_length=22300, null=True)),
                (
                    "redirect_url",
                    models.CharField(blank=True, max_length=22300, null=True),
                ),
                (
                    "account_id",
                    models.CharField(blank=True, max_length=22300, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=22300, null=True)),
                ("active", models.BooleanField(default=True)),
                ("ttl", models.IntegerField(blank=True, null=True)),
                ("expiring", models.DateTimeField(blank=True, null=True)),
                ("app_id", models.CharField(max_length=100, null=True)),
                ("client_id", models.CharField(max_length=100, null=True)),
                ("client_secret", models.CharField(max_length=100, null=True)),
                ("signing_secret", models.CharField(max_length=100, null=True)),
                ("verification_token", models.CharField(max_length=100, null=True)),
                (
                    "bot_token",
                    fernet_fields.fields.EncryptedTextField(blank=True, max_length=10000, null=True),
                ),
                ("bot_id", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduledAccess",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration",
                    models.IntegerField(
                        choices=[
                            (0, "Slack"),
                            (1, "Slack Account"),
                            (2, "Google"),
                            (3, "GoogleLogin"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "pending"),
                            (1, "completed"),
                            (2, "waiting on user"),
                        ]
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=22300, null=True)),
            ],
        ),
    ]
