# Generated by Django 3.2.8 on 2021-10-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    def fix_none_fields(apps, schema_editor):
        AccessToken = apps.get_model("integrations", "accesstoken")
        AccessToken.objects.filter(account_id__isnull=True).update(account_id="")
        AccessToken.objects.filter(app_id__isnull=True).update(app_id="")
        AccessToken.objects.filter(base_url__isnull=True).update(base_url="")
        AccessToken.objects.filter(bot_id__isnull=True).update(bot_id="")
        AccessToken.objects.filter(bot_token__isnull=True).update(bot_token="")
        AccessToken.objects.filter(client_id__isnull=True).update(client_id="")
        AccessToken.objects.filter(client_secret__isnull=True).update(client_secret="")
        AccessToken.objects.filter(name__isnull=True).update(name="")
        AccessToken.objects.filter(refresh_token__isnull=True).update(refresh_token="")
        AccessToken.objects.filter(signing_secret__isnull=True).update(signing_secret="")
        AccessToken.objects.filter(token__isnull=True).update(token="")
        AccessToken.objects.filter(refresh_token__isnull=True).update(refresh_token="")

    dependencies = [
        ('integrations', '0004_auto_20200924_1309'),
    ]

    operations = [
        migrations.RunPython(fix_none_fields),
    ]
