# Generated by Django 3.2.10 on 2022-01-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_auto_20220113_2146"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesstoken",
            name="name",
        ),
    ]
