# Generated by Django 3.2.12 on 2022-04-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0011_accesstoken_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="extra_args",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="manifest",
            field=models.JSONField(default=list),
        ),
    ]
