# Generated by Django 3.2.12 on 2022-04-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_auto_20220409_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='manifest',
            field=models.JSONField(default=dict),
        ),
    ]
