# Generated by Django 3.2.12 on 2022-04-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_alter_accesstoken_extra_args'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessToken',
            new_name='Integration',
        ),
    ]
