# Generated by Django 3.2.13 on 2022-05-17 00:05

from django.db import migrations

import misc.fields


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0016_remove_integration_extra_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="extra_args",
            field=misc.fields.EncryptedJSONField(default=dict),
        ),
    ]
