# Generated by Django 3.2.13 on 2022-07-05 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0017_integration_extra_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="enabled_oauth",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="integration",
            name="expiring",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
