# Generated by Django 4.2.5 on 2023-09-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0018_auto_20220705_1915"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="integration",
            field=models.IntegerField(
                choices=[
                    (0, "Slack bot"),
                    (1, "Slack account creation"),
                    (2, "Google account creation"),
                    (3, "Google Login"),
                    (4, "Asana"),
                    (10, "Custom"),
                ]
            ),
        ),
    ]
