# Generated by Django 4.2.5 on 2023-09-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    def set_integration_manifest_type(apps, schema_editor):
        Integration = apps.get_model("integrations", "integration")
        Integration.objects.filter(integration=10).update(manifest_type=0)

    dependencies = [
        ("integrations", "0019_alter_integration_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="manifest_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Provision user accounts or trigger webhooks"),
                    (1, "Import users"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(
            set_integration_manifest_type, reverse_code=migrations.RunPython.noop
        ),
    ]
