# Generated by Django 4.2.5 on 2023-10-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0020_integration_manifest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="manifest_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Provision user accounts or trigger webhooks"),
                    (1, "Sync users"),
                ],
                null=True,
            ),
        ),
    ]
