# Generated by Django 4.2.6 on 2023-10-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0022_alter_integration_manifest_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="manifest",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
