# Generated by Django 4.2.5 on 2023-11-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0022_alter_integration_manifest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationTrackerStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.IntegerField()),
                ("json_response", models.JSONField()),
                ("html_response", models.TextField()),
                ("url", models.TextField()),
                ("post_data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Run the execute part"),
                            (1, "Check if user exists"),
                            (2, "Revoke user"),
                        ]
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
    ]
