# Generated by Django 4.2.5 on 2023-11-28 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0022_alter_integration_manifest_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Run the execute part"),
                            (1, "Check if user exists"),
                            (2, "Revoke user"),
                        ]
                    ),
                ),
                ("ran_at", models.DateTimeField(auto_now_add=True)),
                (
                    "for_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationTrackerStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.IntegerField()),
                ("json_response", models.JSONField()),
                ("text_response", models.TextField()),
                ("url", models.TextField()),
                ("method", models.TextField()),
                ("post_data", models.JSONField()),
                ("headers", models.JSONField()),
                ("error", models.TextField()),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="integrations.integrationtracker",
                    ),
                ),
            ],
        ),
    ]
