# Generated by Django 4.2.5 on 2023-12-11 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0023_integrationtracker_integrationtrackerstep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationtracker",
            name="integration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.integration",
            ),
        ),
    ]
