# Generated by Django 4.2.5 on 2023-11-15 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0023_integrationtrackerstep_integrationtracker"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationtrackerstep",
            name="headers",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="integrationtrackerstep",
            name="method",
            field=models.TextField(default="post"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="integrationtrackerstep",
            name="tracker",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="integrations.integrationtracker",
            ),
            preserve_default=False,
        ),
    ]
