# Generated by Django 4.2.5 on 2023-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0024_integrationtrackerstep_headers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="integrationtrackerstep",
            old_name="html_response",
            new_name="error",
        ),
        migrations.AddField(
            model_name="integrationtrackerstep",
            name="text_response",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
