# Generated by Django 4.2.11 on 2024-03-14 00:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_alter_integrationtracker_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestExistsField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put')], default='GET', max_length=255)),
                ('expected', models.CharField(max_length=255)),
                ('status_code', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('headers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestRevokeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put')], default='GET', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('expected', models.CharField(blank=True, default='', max_length=255)),
                ('status_code', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('headers', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='integration',
            name='is_active',
            field=models.BooleanField(default=True, help_text="If inactive, it's a test/debug integration"),
        ),
        migrations.CreateModel(
            name='ManifestInitialDataField',
            fields=[
                ('index_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_data_form', to='integrations.manifest')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestForm',
            fields=[
                ('index_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CHOICE', 'Choice'), ('INPUT', 'Input')], max_length=7)),
                ('items', models.JSONField(default=list)),
                ('url', models.URLField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put')], default='GET', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('data_from', models.CharField(default='', max_length=255)),
                ('choice_value', models.CharField(default='id', max_length=255)),
                ('choice_name', models.CharField(default='name', max_length=255)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='integrations.manifest')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestExtraUserInfoField',
            fields=[
                ('index_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_user_info', to='integrations.manifest')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestExecute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put')], default='GET', max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('expected', models.CharField(max_length=255)),
                ('store_data', models.JSONField(default=dict)),
                ('continue_if', models.JSONField(default=dict)),
                ('polling', models.JSONField(default=dict)),
                ('save_as_file', models.CharField(blank=True, default='')),
                ('files', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execute', to='integrations.manifest')),
            ],
        ),
        migrations.AddField(
            model_name='manifest',
            name='exists',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.manifestexistsfield'),
        ),
        migrations.AddField(
            model_name='manifest',
            name='revoke',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.manifestrevokefield'),
        ),
        migrations.AddField(
            model_name='integration',
            name='manifest_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.manifest'),
        ),
    ]
