# Generated by Django 4.2.11 on 2024-03-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_manifest_manifestexistsfield_manifestrevokefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestform',
            name='options_source',
            field=models.CharField(choices=[('fixed list', 'Fixed List'), ('fetch url', 'Fetch Url')], default='fixed list'),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='choice_name',
            field=models.CharField(default='name', help_text='The name that should be displayed to the admin as an option.', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='choice_value',
            field=models.CharField(default='id', help_text='The value it should take for using in other parts of the integration', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='data_from',
            field=models.CharField(blank=True, default='', help_text='The property it should use from the response of the url if you need to go deeper into the result.', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='(optionally) This will overwrite the default headers.'),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='id',
            field=models.CharField(help_text='This value can be used in the other calls. Please do not use spaces or weird characters. A single word in capitals is prefered.', max_length=100),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text="Use only if you set type to 'choice'. This is for fixed items (if you don't want to fetch from a URL)"),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='method',
            field=models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put')], default='GET', max_length=255, verbose_name='Request method'),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='name',
            field=models.CharField(help_text='The form label shown to the admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('INPUT', 'Input')], help_text='If you choose choice, you will be able to set the options yourself OR fetch from an external url.', max_length=7),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='url',
            field=models.URLField(blank=True, help_text='The url it should fetch the options from.', max_length=255),
        ),
    ]
