# Generated by Django 5.2.6 on 2025-09-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0025_integration_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="integration",
            field=models.IntegerField(choices=[(0, "Slack bot"), (10, "Custom")]),
        ),
    ]
