# Generated by Django 4.2.5 on 2023-11-15 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "integrations",
            "0025_rename_html_response_integrationtrackerstep_error_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationtracker",
            name="for_user",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
