# Generated by Django 4.2.11 on 2024-03-17 02:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_manifestform_options_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestExists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('DELETE', 'Delete'), ('PUT', 'Put')], default='GET', max_length=255)),
                ('expected', models.CharField(default='', help_text='Either use this or the status code to validate if the user exists', max_length=255, verbose_name='Expected text in the response')),
                ('status_code', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text="Either use this or the 'expected text' to validate if the user exists", size=None)),
                ('headers', models.JSONField(default=dict)),
            ],
        ),
        migrations.RenameModel(
            old_name='ManifestRevokeField',
            new_name='ManifestRevoke',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='headers',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('INPUT', 'Input')], default='INPUT', help_text='If you choose choice, you will be able to set the options yourself OR fetch from an external url.', max_length=7),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='exists',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.manifestexists'),
        ),
        migrations.DeleteModel(
            name='ManifestExistsField',
        ),
    ]
