# Generated by Django 4.2.5 on 2023-11-16 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0026_integrationtracker_for_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationtracker",
            name="ran_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
