# Generated by Django 5.2.6 on 2025-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0026_alter_integration_integration"),
        ("users", "0043_remove_user_department_user_departments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to make it available to all managers",
                to="users.department",
            ),
        ),
    ]
