# Generated by Django 4.2.5 on 2023-11-25 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("integrations", "0027_integrationtracker_ran_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationtracker",
            name="for_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
