# Generated by Django 4.2.11 on 2024-03-17 02:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_alter_manifestexists_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestexists',
            name='status_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text="Either use this or the 'expected text' to validate if the user exists", size=None),
        ),
    ]
