# Generated by Django 4.2.11 on 2024-03-17 02:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0029_alter_manifestexists_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestrevoke',
            name='status_code',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
