# Generated by Django 4.2.11 on 2024-03-18 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0030_alter_manifestrevoke_status_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestInitialData',
            fields=[
                ('index_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(help_text='This value can be used in the other calls. Please do not use spaces or weird characters. A single word in capitals is prefered.', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('secret', models.BooleanField(default=False, help_text='Enable this if the value should always be masked')),
            ],
        ),
        migrations.AlterField(
            model_name='manifest',
            name='headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='manifestexecute',
            name='headers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='manifestexists',
            name='expected',
            field=models.CharField(blank=True, default='', help_text='Either use this or the status code to validate if the user exists', max_length=255, verbose_name='Expected text in the response'),
        ),
        migrations.AlterField(
            model_name='manifestexists',
            name='headers',
            field=models.JSONField(blank=True, default=list, help_text='Without any items, it will use the default'),
        ),
        migrations.AlterField(
            model_name='manifestexists',
            name='url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestrevoke',
            name='headers',
            field=models.JSONField(blank=True, default=list, help_text='Without any items, it will use the default'),
        ),
        migrations.DeleteModel(
            name='ManifestInitialDataField',
        ),
        migrations.AddField(
            model_name='manifestinitialdata',
            name='manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_data_form', to='integrations.manifest'),
        ),
    ]
