# Generated by Django 4.2.11 on 2024-03-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0031_manifestinitialdata_alter_manifest_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifestinitialdata',
            name='description',
            field=models.CharField(default='', help_text='This will be shown under the input field for extra context', max_length=1255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manifestinitialdata',
            name='name',
            field=models.CharField(help_text="Type 'generate' if you want this value to be generated on the fly (different for each execution), will not need to be filled by a user", max_length=255),
        ),
    ]
