# Generated by Django 4.2.11 on 2024-03-18 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0032_manifestinitialdata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='manifest_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.manifest'),
        ),
    ]
