# Generated by Django 4.2.11 on 2024-03-19 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_alter_integration_manifest_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestExtraUserInfo',
            fields=[
                ('index_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(help_text='This value can be used in the other calls. Please do not use spaces or weird characters. A single word in capitals is prefered.', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(help_text='This will be shown under the input field for extra context', max_length=1255)),
                ('manifest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_user_info', to='integrations.manifest')),
            ],
        ),
        migrations.DeleteModel(
            name='ManifestExtraUserInfoField',
        ),
    ]
