# Generated by Django 4.2.11 on 2024-03-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0034_manifestextrauserinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='revoke',
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='choice_name',
            field=models.CharField(blank=True, default='name', help_text='The name that should be displayed to the admin as an option.', max_length=255),
        ),
        migrations.AlterField(
            model_name='manifestform',
            name='choice_value',
            field=models.CharField(blank=True, default='id', help_text='The value it should take for using in other parts of the integration', max_length=255),
        ),
        migrations.AddField(
            model_name='manifest',
            name='revoke',
            field=models.ManyToManyField(null=True, to='integrations.manifestrevoke'),
        ),
    ]
