# Generated by Django 4.2.11 on 2024-03-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_remove_manifest_revoke_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='revoke',
        ),
        migrations.AddField(
            model_name='manifestrevoke',
            name='manifest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoke', to='integrations.manifest'),
        ),
    ]
