# Generated by Django 3.0.1 on 2020-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("misc", "0001_initial"),
        ("sequences", "0003_remove_externalmessage_content_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalmessage",
            name="content_json",
            field=models.ManyToManyField(to="misc.Content"),
        ),
    ]
