# Generated by Django 3.2.8 on 2021-10-23 02:16

from django.db import migrations


class Migration(migrations.Migration):

    def fix_none_fields(apps, schema_editor):
        PendingAdminTask = apps.get_model("sequences", "PendingAdminTask")
        PendingAdminTask.objects.filter(comment__isnull=True).update(comment="")
        PendingAdminTask.objects.filter(email__isnull=True).update(email="")
        PendingAdminTask.objects.filter(slack_user__isnull=True).update(slack_user="")

    dependencies = [
        ('sequences', '0009_externalmessage_subject'),
    ]

    operations = [
        migrations.RunPython(fix_none_fields),
    ]
