# Generated by Django 3.2.8 on 2021-10-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0010_auto_20211023_0216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingadmintask",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=12500),
        ),
        migrations.AlterField(
            model_name="pendingadmintask",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=12500),
        ),
        migrations.AlterField(
            model_name="pendingadmintask",
            name="slack_user",
            field=models.CharField(blank=True, default="", max_length=12500),
        ),
    ]
