# Generated by Django 3.2.10 on 2022-01-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    def move_unconditioned_items_to_separate_block(apps, schema_editor):
        Sequence = apps.get_model('sequences', 'Sequence')
        Condition = apps.get_model('sequences', 'Condition')
        for seq in Sequence.objects.all():
            con = Condition.objects.create(sequence=seq, condition_type=3)
            con.to_do.set(seq.to_do.all())
            con.resources.set(seq.resources.all())
            con.appointments.set(seq.appointments.all())
            con.preboarding.set(seq.preboarding.all())

    dependencies = [
        ('appointments', '0004_alter_appointment_managers'),
        ('preboarding', '0006_alter_preboarding_managers'),
        ('sequences', '0011_auto_20211023_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='appointments',
            field=models.ManyToManyField(to='appointments.Appointment'),
        ),
        migrations.AddField(
            model_name='condition',
            name='preboarding',
            field=models.ManyToManyField(to='preboarding.Preboarding'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='condition_type',
            field=models.IntegerField(choices=[(0, 'After new hire has started'), (1, 'Based on one or more to do item(s)'), (2, 'Before the new hire has started'), (3, 'Without trigger')], default=0),
        ),
        migrations.RunPython(move_unconditioned_items_to_separate_block, reverse_code=migrations.RunPython.noop),
    ]
