# Generated by Django 3.2.12 on 2022-02-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0015_auto_20220221_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalmessage',
            old_name='content',
            new_name='content_no_json',
        ),
    ]
