# Generated by Django 3.2.12 on 2022-02-24 16:22

from django.db import migrations

import misc.fields


class Migration(migrations.Migration):

    dependencies = [
        ("sequences", "0016_rename_content_externalmessage_content_no_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalmessage",
            name="content",
            field=misc.fields.ContentJSONField(default=dict, verbose_name="Content"),
        ),
    ]
