# Generated by Django 3.2.12 on 2022-02-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sequences", "0017_externalmessage_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externalmessage",
            old_name="content",
            new_name="content_json2",
        ),
    ]
