# Generated by Django 3.2.12 on 2022-02-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0018_rename_content_externalmessage_content_json2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalmessage',
            old_name='content_json',
            new_name='content',
        ),
    ]
