# Generated by Django 3.2.12 on 2022-02-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sequences", "0020_rename_content_json2_externalmessage_content_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalmessage",
            name="content",
        ),
    ]
