# Generated by Django 3.2.12 on 2022-03-02 01:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0022_rename_content_no_json_externalmessage_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingEmailMessage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sequences.externalmessage",),
        ),
        migrations.CreateModel(
            name="PendingSlackMessage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sequences.externalmessage",),
        ),
        migrations.CreateModel(
            name="PendingTextMessage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("sequences.externalmessage",),
        ),
    ]
