# Generated by Django 3.2.12 on 2022-03-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sequences",
            "0023_pendingemailmessage_pendingslackmessage_pendingtextmessage",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalmessage",
            name="person_type",
            field=models.IntegerField(
                choices=[(0, "New hire"), (1, "Manager"), (2, "Buddy"), (3, "custom")],
                default=1,
                verbose_name="For",
            ),
        ),
        migrations.AlterField(
            model_name="pendingadmintask",
            name="option",
            field=models.CharField(
                choices=[(0, "No"), (1, "Email"), (2, "Slack")],
                max_length=12500,
                verbose_name="Send email or text to extra user?",
            ),
        ),
    ]
