# Generated by Django 3.2.12 on 2022-04-12 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0015_rename_accesstoken_integration"),
        ("sequences", "0026_alter_pendingadmintask_option"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprovision",
            name="integration_type",
        ),
        migrations.AddField(
            model_name="accountprovision",
            name="integration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integrations.integration",
            ),
        ),
    ]
