# Generated by Django 3.2.12 on 2022-04-22 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sequences", "0027_auto_20220412_0103"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingadmintask",
            name="person_type",
            field=models.IntegerField(
                choices=[(0, "New hire"), (1, "Manager"), (2, "Buddy"), (3, "custom")],
                default=3,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="pendingadmintask",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pick user",
            ),
        ),
    ]
