# Generated by Django 3.2.12 on 2022-04-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0028_auto_20220422_2129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingadmintask",
            name="person_type",
            field=models.IntegerField(
                choices=[(0, "New hire"), (1, "Manager"), (2, "Buddy"), (3, "custom")],
                default=1,
                verbose_name="Assigned to",
            ),
        ),
    ]
