# Generated by Django 3.2.12 on 2022-04-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sequences", "0029_alter_pendingadmintask_person_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingadmintask",
            name="option",
            field=models.IntegerField(
                choices=[(0, "No"), (1, "Email"), (2, "Slack")],
                default=0,
                verbose_name="Send email or Slack message to extra user?",
            ),
        ),
        migrations.AlterField(
            model_name="pendingadmintask",
            name="person_type",
            field=models.IntegerField(
                choices=[(1, "Manager"), (2, "Buddy"), (3, "custom")],
                default=1,
                verbose_name="Assigned to",
            ),
        ),
    ]
