# Generated by Django 3.2.13 on 2022-05-04 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0030_auto_20220422_2244"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pendingadmintask",
            old_name="slack_user",
            new_name="slack_user_old",
        ),
    ]
