# Generated by Django 3.2.13 on 2022-05-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0032_pendingadmintask_slack_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingadmintask',
            name='slack_user_old',
        ),
    ]
