# Generated by Django 3.2.13 on 2022-05-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0015_rename_accesstoken_integration"),
        ("sequences", "0033_remove_pendingadmintask_slack_user_old"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AccountProvision",
            new_name="IntegrationConfig",
        ),
        migrations.RemoveField(
            model_name="condition",
            name="account_provisions",
        ),
        migrations.AddField(
            model_name="condition",
            name="integration_configs",
            field=models.ManyToManyField(to="sequences.IntegrationConfig"),
        ),
    ]
