# Generated by Django 3.2.13 on 2022-05-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0036_integrationconfig_additional_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalmessage",
            name="person_type",
            field=models.IntegerField(
                choices=[(0, "New hire"), (1, "Manager"), (2, "Buddy"), (3, "Custom")],
                default=1,
                verbose_name="For",
            ),
        ),
        migrations.AlterField(
            model_name="pendingadmintask",
            name="person_type",
            field=models.IntegerField(
                choices=[(1, "Manager"), (2, "Buddy"), (3, "Custom")],
                default=1,
                verbose_name="Assigned to",
            ),
        ),
    ]
