# Generated by Django 3.2.13 on 2022-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0037_auto_20220520_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingadmintask',
            name='date',
            field=models.DateField(blank=True, default='2022-06-06', null=True, verbose_name='Due date'),
        ),
    ]
