# Generated by Django 4.2.5 on 2023-09-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0040_auto_20220811_2150"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="condition_admin_tasks",
            field=models.ManyToManyField(
                related_name="condition_triggers",
                to="sequences.pendingadmintask",
                verbose_name="Trigger after these admin todo items have been completed:",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="condition_type",
            field=models.IntegerField(
                choices=[
                    (0, "After new hire has started"),
                    (1, "Based on one or more to do item(s)"),
                    (2, "Before the new hire has started"),
                    (3, "Without trigger"),
                    (4, "Based on one or more admin tasks"),
                ],
                default=0,
                verbose_name="Block type",
            ),
        ),
    ]
