# Generated by Django 4.2.5 on 2023-09-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0041_condition_condition_admin_tasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingadmintask",
            name="template",
            field=models.BooleanField(
                default=False,
                help_text="Should always be False, for now it's just here to comply with other functions (like duplicate)",
            ),
        ),
    ]
