# Generated by Django 4.2.6 on 2023-10-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0041_condition_condition_admin_tasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sequence",
            name="category",
            field=models.IntegerField(
                choices=[(0, "Onboarding sequence"), (1, "Offboarding sequence")],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
