# Generated by Django 4.2.6 on 2023-10-26 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sequences", "0042_sequence_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconfig",
            name="assigned_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user_integration",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pick user",
            ),
        ),
        migrations.AddField(
            model_name="integrationconfig",
            name="person_type",
            field=models.IntegerField(
                choices=[(1, "Manager"), (2, "Buddy"), (3, "Custom")],
                default=1,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="days",
            field=models.IntegerField(
                default=1, verbose_name="Amount of days before/after"
            ),
        ),
    ]
