# Generated by Django 4.2.6 on 2023-11-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0001_initial"),
        ("sequences", "0042_integrationconfig_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="hardware",
            field=models.ManyToManyField(to="hardware.hardware"),
        ),
    ]
