# Generated by Django 4.2.6 on 2023-10-28 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sequences", "0043_integrationconfig_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_user_integration",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pick user",
            ),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="person_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Manager"), (2, "Buddy"), (3, "Custom")],
                help_text="Leave empty to automatically check the integration as created/removed.",
                null=True,
                verbose_name="Assigned to",
            ),
        ),
    ]
