# Generated by Django 4.2.5 on 2023-11-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0043_condition_hardware"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalmessage",
            name="person_type",
            field=models.IntegerField(
                choices=[
                    (0, "New hire/User to be offboarded"),
                    (1, "Manager"),
                    (2, "Buddy"),
                    (3, "Custom"),
                    (4, "Slack channel"),
                ],
                default=1,
                verbose_name="For",
            ),
        ),
    ]
