# Generated by Django 4.2.5 on 2023-11-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0044_alter_externalmessage_person_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="condition_type",
            field=models.IntegerField(
                choices=[
                    (0, "After new hire has started"),
                    (1, "Based on one or more to do item(s)"),
                    (2, "Before the new hire has started"),
                    (3, "Without trigger"),
                    (4, "Based on one or more admin tasks"),
                    (5, "When all integrations have been revoked"),
                ],
                default=0,
                verbose_name="Block type",
            ),
        ),
    ]
