# Generated by Django 4.2.20 on 2025-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0045_alter_condition_condition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='active',
            field=models.BooleanField(default=True, help_text='If disabled, this sequence will not be automatically assigned', verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='sequence',
            name='manager_sequence',
            field=models.BooleanField(default=False, help_text='If enabled, this sequence will be automatically assigned to new managers', verbose_name='Manager sequence'),
        ),
    ]
