# Generated by Django 3.0.1 on 2020-06-06 20:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(blank=True, max_length=100)),
                ('ext', models.CharField(max_length=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'p'), ('h1', 'h1'), ('h2', 'h2'), ('h3', 'h3'), ('quote', 'quote'), ('youtube', 'youtube'), ('ul', 'ul'), ('ol', 'ol'), ('hr', 'hr'), ('file', 'file'), ('image', 'image'), ('question', 'question')], max_length=100)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name=models.CharField(max_length=100000))),
                ('content', models.CharField(blank=True, max_length=100000)),
                ('answer', models.CharField(blank=True, max_length=10000)),
                ('files', models.ManyToManyField(to='misc.File')),
            ],
        ),
    ]
