# Generated by Django 3.1.8 on 2021-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0003_auto_20201013_0149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="type",
            field=models.CharField(
                choices=[
                    ("p", "p"),
                    ("h1", "h1"),
                    ("h2", "h2"),
                    ("h3", "h3"),
                    ("quote", "quote"),
                    ("youtube", "youtube"),
                    ("ul", "ul"),
                    ("ol", "ol"),
                    ("hr", "hr"),
                    ("file", "file"),
                    ("image", "image"),
                    ("video", "video"),
                    ("question", "question"),
                ],
                max_length=100,
            ),
        ),
    ]
