# Generated by Django 3.2.12 on 2022-02-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0004_auto_20210511_1242"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Content",
        ),
    ]
