# Generated by Django 3.2.8 on 2021-11-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("to_do", "0005_alter_todo_content_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_to_do.todo_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
