# Generated by Django 3.2.8 on 2021-11-11 02:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_todo_polymorphic_ctype'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
                ('templates', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='polymorphic_ctype',
        ),
    ]
