# Generated by Django 3.2.8 on 2021-11-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0007_auto_20211111_0237'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='todo',
            managers=[
            ],
        ),
    ]
