# Generated by Django 3.2.10 on 2022-01-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0008_alter_todo_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='form',
            field=models.JSONField(default=list, verbose_name=models.TextField(default='[]')),
        ),
    ]
