# Generated by Django 3.2.10 on 2022-01-28 00:04

from django.db import migrations

import misc.fields


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0009_alter_todo_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="content_json",
            field=misc.fields.ContentJSONField(default=dict),
        ),
    ]
