# Generated by Django 3.2.10 on 2022-01-31 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    def move_text_to_foreignfield(apps, schema_editor):
        SlackChannel = apps.get_model("slack_bot", "SlackChannel")
        ToDo = apps.get_model("to_do", "ToDo")
        Organization = apps.get_model("organization", "Organization")

        # Not necessarily related, but let's fix the default channel for organization
        # as well
        slack_channel, _ = SlackChannel.objects.get_or_create(name="general")
        # Check if organization exists. If not, then the site has not been set up
        # yet and then just drop everything else
        try:
            org = Organization.object.get()
        except:  # noqa E722
            # Org does not exist yet
            return

        org.slack_default_channel = slack_channel
        org.save()

        # Update to do items
        for todo in ToDo.objects.all():
            if todo.channel != "":
                slack_channel, _ = SlackChannel.objects.get_or_create(name=todo.channel)
                todo.slack_channel = slack_channel
                todo.save()

    dependencies = [
        ("slack_bot", "0001_initial"),
        ("to_do", "0010_alter_todo_content_json"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="slack_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="slack_bot.slackchannel",
            ),
        ),
        migrations.RunPython(move_text_to_foreignfield),
    ]
