# Generated by Django 3.2.10 on 2022-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0012_remove_todo_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='form',
            field=models.JSONField(default=list),
        ),
    ]
