# Generated by Django 3.2.10 on 2022-02-09 00:40

from django.db import migrations

# Ignore - used to be a custom migration, but got stuck in the middle.
class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0013_alter_todo_form'),
    ]

    operations = [
    ]
