# Generated by Django 3.2.10 on 2022-02-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0014_auto_20220209_0040"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="content",
        ),
    ]
