# Generated by Django 3.2.10 on 2022-02-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0015_remove_todo_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='content_json',
            new_name='content',
        ),
    ]
