# Generated by Django 3.2.12 on 2022-02-21 13:38

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import misc.fields


class Migration(migrations.Migration):
    dependencies = [
        ("slack_bot", "0001_initial"),
        ("to_do", "0017_auto_20220209_0122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="content",
            field=misc.fields.ContentJSONField(default=dict, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_on_day",
            field=models.IntegerField(default=0, verbose_name="Due on day"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=240, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="todo",
            name="send_back",
            field=models.BooleanField(
                default=False,
                verbose_name=(
                    "Post new hire's answers from form (if applicable) back to Slack "
                    "channel"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="slack_channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="slack_bot.slackchannel",
                verbose_name="Slack channel",
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=10200),
                blank=True,
                size=None,
                verbose_name="Tags",
            ),
        ),
    ]
