# Generated by Django 3.2.12 on 2022-03-10 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0018_auto_20220221_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='form',
        ),
    ]
