# Generated by Django 3.2.13 on 2022-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0019_remove_todo_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_on_day',
            field=models.IntegerField(default=1, verbose_name='Due on day'),
        ),
    ]
