# Generated by Django 5.2.6 on 2025-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("to_do", "0020_alter_todo_due_on_day"),
        ("users", "0043_remove_user_department_user_departments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="todo",
            name="departments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to make it available for all managers/admins",
                to="users.department",
            ),
        ),
    ]
