# Generated by Django 5.2.6 on 2025-09-22 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0022_alter_todo_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('name',)},
        ),
    ]
