# Generated by Django 3.0.1 on 2020-06-06 20:14

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sequences', '0001_initial'),
        ('to_do', '0001_initial'),
        ('appointments', '0001_initial'),
        ('resources', '0001_initial'),
        ('badges', '0001_initial'),
        ('introductions', '0001_initial'),
        ('misc', '0001_initial'),
        ('preboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('position', models.CharField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=300, null=True)),
                ('slack_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slack_channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=100000, null=True)),
                ('linkedin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('timezone', models.CharField(default='', max_length=1000)),
                ('language', models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('fr', 'French'), ('de', 'German'), ('tr', 'Turkish'), ('pt', 'Portuguese'), ('es', 'Spanish')], default='en', max_length=5)),
                ('role', models.IntegerField(choices=[(0, 'New Hire'), (1, 'Admin'), (2, 'Manager'), (3, 'Other')], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_introduced_to_colleagues', models.BooleanField(default=False)),
                ('sent_preboarding_details', models.BooleanField(default=False)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('start_day', models.DateField(blank=True, help_text='First working day', null=True)),
                ('unique_url', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('appointments', models.ManyToManyField(to='appointments.Appointment')),
                ('badges', models.ManyToManyField(to='badges.Badge')),
                ('buddy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_hire_buddy', to=settings.AUTH_USER_MODEL)),
                ('conditions', models.ManyToManyField(to='sequences.Condition')),
                ('introductions', models.ManyToManyField(to='introductions.Introduction')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_hire_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name=models.CharField(default='[]', max_length=100000))),
                ('reminded', models.DateTimeField(null=True)),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_do', to='to_do.ToDo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_do_new_hire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('reminded', models.DateTimeField(null=True)),
                ('completed_course', models.BooleanField(default=False)),
                ('answers', models.ManyToManyField(to='resources.CourseAnswer')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_new_hire', to='resources.Resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_hire_resource', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreboardingUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', django.contrib.postgres.fields.jsonb.JSONField(default=list, verbose_name=models.CharField(default='[]', max_length=100000))),
                ('completed', models.BooleanField(default=False)),
                ('preboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preboarding_new_hire', to='preboarding.Preboarding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_hire_preboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewHireWelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_colleague', to=settings.AUTH_USER_MODEL)),
                ('new_hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_new_hire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='preboarding',
            field=models.ManyToManyField(through='users.PreboardingUser', to='preboarding.Preboarding'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.File'),
        ),
        migrations.AddField(
            model_name='user',
            name='resources',
            field=models.ManyToManyField(through='users.ResourceUser', to='resources.Resource'),
        ),
        migrations.AddField(
            model_name='user',
            name='to_do',
            field=models.ManyToManyField(through='users.ToDoUser', to='to_do.ToDo'),
        ),
    ]
