# Generated by Django 3.1.2 on 2020-10-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200924_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preboardinguser",
            name="form",
            field=models.JSONField(
                default=list,
                verbose_name=models.TextField(default="[]", max_length=100000),
            ),
        ),
        migrations.AlterField(
            model_name="todouser",
            name="form",
            field=models.JSONField(
                default=list, verbose_name=models.TextField(default="[]")
            ),
        ),
    ]
