# Generated by Django 3.1.2 on 2020-10-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20201013_0149"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.TextField(default=""),
        ),
    ]
