# Generated by Django 3.1.2 on 2020-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.TextField(blank=True, default=""),
        ),
    ]
