# Generated by Django 3.1.3 on 2020-12-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201128_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_email',
            field=models.EmailField(blank=True, default='', max_length=200),
        ),
    ]
