# Generated by Django 3.1.8 on 2021-04-15 14:31

from django.db import migrations, models
import fernet_fields.fields
import uuid
import pyotp

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_seen_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_recovery_key',
            field=fernet_fields.fields.EncryptedTextField(default=uuid.uuid4()),
        ),
        migrations.AddField(
            model_name='user',
            name='requires_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=fernet_fields.fields.EncryptedTextField(default=pyotp.random_base32()),
        ),
    ]
