# Generated by Django 3.1.8 on 2021-05-11 12:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from misc import fernet_fields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_auto_20210415_1431"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp_recovery_key",
        ),
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=fernet_fields.EncryptedTextField(
                default="7OBYIHJ4MVEH54FVTEK4XBMO5IILQFFM"  # gets replaced in 0012
            ),
        ),
        migrations.CreateModel(
            name="OTPRecoveryKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", fernet_fields.EncryptedTextField(default=uuid.uuid4)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_otp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
