# Generated by Django 3.1.8 on 2021-05-11 12:59

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210511_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=fernet_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
