# Generated by Django 3.1.8 on 2021-06-04 20:19

from django.db import migrations
import pyotp

class Migration(migrations.Migration):

    def regenerate_all_secrets(apps, schema_editor):
        User = apps.get_model('users', 'User')
        for user in User.objects.all():
            user.totp_secret = pyotp.random_base32()
            user.save() 
    
    dependencies = [
        ('users', '0011_auto_20210511_1259'),
    ]

    operations = [
        migrations.RunPython(regenerate_all_secrets),
    ]
