# Generated by Django 3.2.8 on 2021-10-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    def fix_none_fields(apps, schema_editor):
        User = apps.get_model("users", "User")
        User.objects.filter(phone__isnull=True).update(phone="")
        User.objects.filter(position__isnull=True).update(position="")
        User.objects.filter(slack_channel_id__isnull=True).update(slack_channel_id="")
        User.objects.filter(slack_user_id__isnull=True).update(slack_user_id="")

    dependencies = [
        ('users', '0012_auto_20210604_2019'),
    ]

    operations = [
        migrations.RunPython(fix_none_fields),
    ]
