# Generated by Django 3.2.10 on 2022-01-28 01:00

from django.db import migrations


class Migration(migrations.Migration):
    def set_users_without_password_inactive(apps, schema_editor):
        User = apps.get_model("users", "User")
        User.objects.filter(password="").update(is_active=False)

    dependencies = [
        ("users", "0016_auto_20211111_0256"),
    ]

    operations = [
        migrations.RunPython(set_users_without_password_inactive),
    ]
