# Generated by Django 3.2.10 on 2022-02-09 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    def move_departments(apps, schema_editor):
        User = apps.get_model("users", "User")
        Department = apps.get_model("users", "Department")
        # technically, we could have used an update here and make less connections, but since it's just a one-off task,
        # let's not make it more complex than it needs to be
        for user in User.objects.all():

            # Skip all items that have no department
            if user.department == "":
                continue

            dep, _ = Department.objects.get_or_create(name=user.department)
            user.deparment_obj = dep
            user.save()

    dependencies = [
        ("users", "0017_auto_20220128_0100"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="department_obj",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.department",
            ),
        ),
        migrations.RunPython(move_departments),
    ]
