# Generated by Django 3.2.10 on 2022-02-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department_obj',
            new_name='department',
        ),
    ]
