# Generated by Django 3.2.10 on 2022-02-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_department_obj_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preboardinguser',
            name='form',
            field=models.JSONField(default=list),
        ),
    ]
