# Generated by Django 3.2.13 on 2022-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220604_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_day',
            field=models.DateField(blank=True, default='2022-06-06', help_text='First working day', null=True, verbose_name='Start date'),
        ),
    ]
