# Generated by Django 3.2.13 on 2022-08-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_auto_20220804_1526"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="extra_fields",
            field=models.JSONField(default=dict),
        ),
    ]
