# Generated by Django 3.2.18 on 2023-05-07 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ldap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Last name'),
            preserve_default=False,
        ),
    ]
