# Generated by Django 3.2.16 on 2023-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Newhire"), (1, "Admin"), (2, "Manager"), (3, "Other")],
                default=3,
                help_text=(
                    "An administrator has access to everything."
                    "A manager has only access to their new hires and their tasks."
                ),
                verbose_name="Role",
            ),
        ),
    ]
