# Generated by Django 3.2.16 on 2023-02-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "New hire"),
                    (1, "Administrator"),
                    (2, "Manager"),
                    (3, "Other"),
                ],
                default=3,
                help_text=(
                    "An administrator has access to everything."
                    "A manager has only access to their new hires and their tasks."
                ),
                verbose_name="Role",
            ),
        ),
    ]
