# Generated by Django 4.2.5 on 2023-09-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_alter_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "New hire"),
                    (1, "Administrator"),
                    (2, "Manager"),
                    (3, "Other"),
                ],
                default=3,
                help_text=(
                    "An administrator has access to everything. "
                    "A manager has only access to their new hires and their tasks."
                ),
                verbose_name="Role",
            ),
        ),
    ]
