# Generated by Django 4.2.6 on 2023-10-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0023_alter_integration_manifest"),
        ("users", "0035_userintegration_user_integrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="userintegration",
            name="revoked",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="userintegration",
            unique_together={("user", "integration")},
        ),
        migrations.RemoveField(
            model_name="userintegration",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="userintegration",
            name="revoked_at",
        ),
    ]
