# Generated by Django 4.2.6 on 2023-10-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_userintegration_revoked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userintegration",
            name="revoked",
            field=models.BooleanField(default=False),
        ),
    ]
