# Generated by Django 4.2.5 on 2023-11-07 15:36

from allauth.account.models import EmailAddress
from allauth.mfa.models import Authenticator
from allauth.mfa.utils import encrypt
from django.contrib.auth import get_user_model
from django.db import migrations


class Migration(migrations.Migration):
    def move_to_allauth(apps, schema_editor):
        User = apps.get_model("users", "User")

        # verify all emails
        EmailAddress.objects.bulk_create(
            [
                EmailAddress(user=user, email=user.email, verified=True, primary=True)
                for user in get_user_model().objects.all()
            ]
        )

        # move 2fa to allauth
        authenticators = []
        for user in User.objects.filter(requires_otp=True):
            authenticators.append(
                Authenticator(
                    user=user,
                    type=Authenticator.Type.TOTP,
                    data={"secret": encrypt(user.totp_secret)},
                )
            )
            otp_keys = user.user_otp.filter(is_used=False).values_list("key", flat=True)
            authenticators.append(
                Authenticator(
                    user=user,
                    type=Authenticator.Type.RECOVERY_CODES,
                    data={
                        "seed": encrypt(user.totp_secret),
                        "used_mask": 0,
                        "migrated_codes": [encrypt(key) for key in otp_keys],
                    },
                )
            )

    dependencies = [
        ("users", "0036_user_termination_date"),
    ]

    operations = [
        migrations.RunPython(move_to_allauth, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="requires_otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="totp_secret",
        ),
        migrations.DeleteModel(
            name="OTPRecoveryKey",
        ),
    ]
