# Generated by Django 4.2.6 on 2023-11-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hardware", "0001_initial"),
        ("users", "0036_user_termination_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hardware",
            field=models.ManyToManyField(
                related_name="user_hardware", to="hardware.hardware"
            ),
        ),
    ]
