# Generated by Django 4.2.5 on 2023-11-10 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_delete_otprecoverykey"),
        ("users", "0037_user_hardware"),
    ]

    operations = []
