# Generated by Django 4.2.5 on 2023-11-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_user_hardware"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ran_integrations_condition",
            field=models.BooleanField(default=False),
        ),
    ]
