# Generated by Django 4.2.20 on 2025-03-09 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_merge_0037_delete_otprecoverykey_0037_user_hardware"),
        ("users", "0040_alter_user_timezone"),
    ]

    operations = []
