# Generated by Django 5.2.6 on 2025-09-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_remove_user_requires_otp_remove_user_totp_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="users", to="users.department"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
