# Generated by Django 5.2.6 on 2025-09-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    def move_department(apps, schema_editor):
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            if user.department is not None:
                user.departments.add(user.department)
                user.save()

    dependencies = [
        ("users", "0042_remove_user_requires_otp_remove_user_totp_secret_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.department"
            ),
        ),
        migrations.RunPython(move_department, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "New hire"),
                    (1, "Administrator"),
                    (2, "Manager"),
                    (3, "Other"),
                ],
                default=3,
                help_text="An administrator has access to everything. A manager has no access to settings and only access to the items in their departments",
                verbose_name="Role",
            ),
        ),
    ]
