# Generated by Django 5.2.6 on 2025-09-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_user_departments_alter_department_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.department"
            ),
        ),
    ]
