# Generated by Django 5.2.6 on 2025-09-25 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0043_remove_user_department_user_departments_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ("name",)},
        ),
    ]
