# Generated by Django 5.2.7 on 2025-10-14 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0046_alter_sequence_options_sequence_departments'),
        ('users', '0044_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sequences',
            field=models.ManyToManyField(related_name='+', to='sequences.sequence'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='users.department')),
                ('sequences', models.ManyToManyField(related_name='roles', to='sequences.sequence')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
