# Generated by Django 5.2.7 on 2025-12-01 03:22

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


class Migration(migrations.Migration):
    def set_user_condition_role_start_date(apps, schema_editor):
        UserCondition = apps.get_model("users", "UserCondition")
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            UserCondition.objects.filter(user=user).update(
                role_start_date=user.start_day
            )

    def clear_conditions_for_normal_users(apps, schema_editor):
        User = apps.get_model("users", "User")
        for user in User.objects.exclude(role=get_user_model().Role.NEWHIRE).exclude(
            termination_date__isnull=False
        ):
            user.conditions.clear()

    def set_resource_user_role_start_date(apps, schema_editor):
        ResourceUser = apps.get_model("users", "ResourceUser")
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            ResourceUser.objects.filter(user=user).update(
                role_start_date=user.start_day
            )

    def set_to_do_user_role_start_date(apps, schema_editor):
        ToDoUser = apps.get_model("users", "ToDoUser")
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            ToDoUser.objects.filter(user=user).update(role_start_date=user.start_day)

    dependencies = [
        ('sequences', '0046_alter_sequence_options_sequence_departments'),
        ('users', '0044_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sequences',
            field=models.ManyToManyField(blank=True, related_name='+', to='sequences.sequence'),
        ),
        migrations.AddField(
            model_name='resourceuser',
            name='role_start_date',
            field=models.DateField(default=None, help_text='Date used to calculate due date for to do item.', null=True),
        ),
        migrations.AddField(
            model_name='todouser',
            name='role_start_date',
            field=models.DateField(default=None, help_text='Date used to calculate due date for to do item.', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DepartmentRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='users.department')),
                ('sequences', models.ManyToManyField(blank=True, related_name='roles', to='sequences.sequence')),
                ('users', models.ManyToManyField(related_name='department_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from UserCondition._meta.db_table.
                migrations.RunSQL(
                    sql="ALTER TABLE users_user_conditions RENAME TO users_usercondition",
                    reverse_sql="ALTER TABLE users_usercondition RENAME TO users_user_conditions",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='UserCondition',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sequences.condition')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'unique_together': {('user', 'condition')},
                    },
                ),
                migrations.AlterField(
                    model_name='user',
                    name='conditions',
                    field=models.ManyToManyField(through='users.UserCondition', to='sequences.condition'),
                ),
            ]
        ),
        migrations.AddField(
            model_name="UserCondition",
            name="role_start_date",
            field=models.DateField(default=None, help_text='Date used to calculate when to trigger the condition', null=True),
        ),
        migrations.RunPython(
            set_user_condition_role_start_date, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            clear_conditions_for_normal_users, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_resource_user_role_start_date, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_to_do_user_role_start_date, reverse_code=migrations.RunPython.noop
        ),
    ]
