# Generated by Django 5.2.7 on 2025-10-21 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sequences", "0046_alter_sequence_options_sequence_departments"),
        ("users", "0045_department_sequences_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="sequences",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="sequences.sequence"
            ),
        ),
        migrations.CreateModel(
            name="DepartmentRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roles",
                        to="users.department",
                    ),
                ),
                (
                    "sequences",
                    models.ManyToManyField(
                        blank=True, related_name="roles", to="sequences.sequence"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="department_roles", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
