# Generated by Django 5.2.6 on 2025-09-23 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0045_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
    ]
