# Generated by Django 5.2.7 on 2025-10-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0046_alter_department_sequences_departmentrole_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
