# Generated by Django 5.2.8 on 2025-11-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


class Migration(migrations.Migration):
    def set_user_condition_role_start_date(apps, schema_editor):
        UserCondition = apps.get_model("users", "UserCondition")
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            UserCondition.objects.filter(user=user).update(
                role_start_date=user.start_day
            )

    def clear_conditions_for_normal_users(apps, schema_editor):
        User = apps.get_model("users", "User")
        for user in User.objects.exclude(role=get_user_model().Role.NEWHIRE).exclude(
            termination_date__isnull=False
        ):
            user.conditions.clear()

    dependencies = [
        ("sequences", "0046_alter_sequence_options_sequence_departments"),
        ("users", "0047_alter_department_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Old table name from checking with sqlmigrate, new table
                # name from UserCondition._meta.db_table.
                migrations.RunSQL(
                    sql="ALTER TABLE users_user_conditions RENAME TO users_usercondition",
                    reverse_sql="ALTER TABLE users_usercondition RENAME TO users_user_conditions",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="UserCondition",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "condition",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="sequences.condition",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "unique_together": {("user", "condition")},
                    },
                ),
                migrations.AlterField(
                    model_name="user",
                    name="conditions",
                    field=models.ManyToManyField(
                        through="users.UserCondition", to="sequences.condition"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="UserCondition",
            name="base_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.RunPython(
            set_user_condition_role_start_date, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            clear_conditions_for_normal_users, reverse_code=migrations.RunPython.noop
        ),
    ]
