# Generated by Django 5.2.8 on 2025-11-27 03:20

from django.contrib.auth import get_user_model
from django.db import migrations


class Migration(migrations.Migration):
    def clear_conditions_for_normal_users(apps, schema_editor):
        User = apps.get_model("users", "User")
        for user in User.objects.exclude(role=get_user_model().Role.NEWHIRE).exclude(
            termination_date__isnull=False
        ):
            user.conditions.clear()

    dependencies = [
        ("users", "0047_alter_department_name"),
    ]

    operations = [
        migrations.RunPython(
            clear_conditions_for_normal_users, reverse_code=migrations.RunPython.noop
        ),
    ]
