# Generated by Django 5.2.8 on 2025-11-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    def set_resource_user_role_start_date(apps, schema_editor):
        ResourceUser = apps.get_model("users", "ResourceUser")
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            ResourceUser.objects.filter(user=user).update(
                role_start_date=user.start_day
            )

    def set_to_do_user_role_start_date(apps, schema_editor):
        ToDoUser = apps.get_model("users", "ToDoUser")
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            ToDoUser.objects.filter(user=user).update(role_start_date=user.start_day)

    dependencies = [
        ("users", "0048_usercondition_alter_user_conditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceuser",
            name="base_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="todouser",
            name="base_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.RunPython(
            set_resource_user_role_start_date, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            set_to_do_user_role_start_date, reverse_code=migrations.RunPython.noop
        ),
    ]
