# Generated by Django 5.2.8 on 2025-11-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0050_alter_resourceuser_base_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourceuser",
            name="base_date",
        ),
        migrations.RemoveField(
            model_name="todouser",
            name="base_date",
        ),
        migrations.RemoveField(
            model_name="usercondition",
            name="base_date",
        ),
        migrations.AddField(
            model_name="resourceuser",
            name="role_start_date",
            field=models.DateField(
                default=None,
                help_text="Date used to calculate due date for to do item.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="todouser",
            name="role_start_date",
            field=models.DateField(
                default=None,
                help_text="Date used to calculate due date for to do item.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usercondition",
            name="role_start_date",
            field=models.DateField(
                default=None,
                help_text="Date used to calculate when to trigger the condition",
                null=True,
            ),
        ),
    ]
