# Generated by Django 3.2.18 on 2023-05-24 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20230506_2155'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='is_ldap',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
