# Generated by Django 3.1.3 on 2020-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0007_remove_sequence_introductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='auto_add',
            field=models.BooleanField(default=False),
        ),
    ]
