# Generated by Django 3.1.3 on 2020-12-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0008_sequence_auto_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('asana', 'Asana'), ('google', 'Google'), ('slack', 'Slack')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='integrations',
            field=models.ManyToManyField(to='sequences.AccountCreation'),
        ),
    ]
