# Generated by Django 3.1.3 on 2020-12-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0010_auto_20201210_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreation',
            name='additional_data',
            field=models.JSONField(default=dict, verbose_name=models.TextField(blank=True)),
        ),
        migrations.AlterField(
            model_name='accountcreation',
            name='integration_type',
            field=models.CharField(choices=[('asana', 'Add Asana account to team'), ('google', 'Create Google account'), ('slack', 'Create Slack account')], max_length=10),
        ),
    ]
